import mysql.connector
db = mysql.connector.connect(
    host = "localhost",
    user="root",
    passwd = '',
    database="Project"
)
mycursor = db.cursor()
sqlFomular = "INSERT INTO Context (name,context,description) VALUES (%s,%s,%s)"
multi = [
    ("test.xml","""
    <DCRModel>
<id>220802</id>
<title>Healthcare Workflow</title>
<events>
<id>play</id>
</events>
<events>
<id>claimReward</id>
</events>
<rules>
<type>condition</type>
<source>play</source>
<target>claimReward</target>
</rules>
<rules>
<type>include</type>
<source>claimReward</source>
<target>play</target>
</rules>
</DCRModel>
    ""","Use for SC1"),

("test.xml","""
<DCRModel>
<id>220802</id>
<title>Healthcare Workflow</title>
<events>
<id>Treatment</id>
<type>nesting</type>
</events>
<events>
<id>ManagePrescription</id>
<parent>Treatment</parent>
<type>nesting</type>
</events>
<events>
<id>MedicinePreparation</id>
<parent>Treatment</parent>
<type>nesting</type>
</events>
<events>
<id>AdministerMedicine</id>
<parent>Treatment</parent>
<type>nesting</type>
</events>
<events>
<id>Trust</id>
<parent>AdministerMedicine</parent>
<type>nesting</type>
</events>
<events>
<id>Edit</id>
<parent>ManagePrescription</parent>
</events>
<events>
<id>Cancel</id>
<parent>ManagePrescription</parent>
</events>
<events>
<id>PrescribeMedicine</id>
<parent>Treatment</parent>
</events>
<events>
<id>SignDoctor</id>
<parent>Treatment</parent>
</events>
<events>
<id>DontTrustPrescription(N)</id>
<parent>Treatment</parent>
</events>
<events>
<id>GiveMedicine</id>
<parent>AdministerMedicine</parent>
</events>
<events>
<id>SignNurseI</id>
<parent>Trust</parent>
</events>
<events>
<id>SignNurseII</id>
<parent>Trust</parent>
</events>
<events>
<id>DontTrustPrescription(CP)</id>
<parent>MedicinePreparation</parent>
</events>
<events>
<id>AcceptPrescription</id>
<parent>MedicinePreparation</parent>
</events>
<events>
<id>MakePreparation</id>
<parent>MedicinePreparation</parent>
</events>
<events>
<id>SignPA</id>
<parent>MedicinePreparation</parent>
</events>
<events>
<id>SignCP</id>
<parent>MedicinePreparation</parent>
</events>
<events>
<id>DontTrustPreparation(CP)</id>
<parent>MedicinePreparation</parent>
</events>
<events>
<id>DontTrustPreparation(N)</id>
<parent>MedicinePreparation</parent>
</events>
<rules>
<type>include</type>
<source>PrescribeMedicine</source>
<target>ManagePrescription</target>
</rules>
<rules>
<type>response</type>
<source>Edit</source>
<target>SignDoctor</target>
</rules>
<rules>
<type>exclude</type>
<source>Cancel</source>
<target>Treatment</target>
</rules>
<rules>
<type>response</type>
<source>PrescribeMedicine</source>
<target>SignDoctor</target>
</rules>
<rules>
<type>exclude</type>
<source>PrescribeMedicine</source>
<target>PrescribeMedicine</target>
</rules>
<rules>
<type>condition</type>
<source>PrescribeMedicine</source>
<target>SignDoctor</target>
</rules>
<rules>
<type>response</type>
<source>PrescribeMedicine</source>
<target>GiveMedicine</target>
</rules>
<rules>
<type>milestone</type>
<source>SignDoctor</source>
<target>MedicinePreparation</target>
</rules>
<rules>
<type>condition</type>
<source>SignDoctor</source>
<target>MedicinePreparation</target>
</rules>
<rules>
<type>response</type>
<source>SignDoctor</source>
<target>AcceptPrescription</target>
</rules>
<rules>
<type>response</type>
<source>SignDoctor</source>
<target>DontTrustPrescription(N)</target>
</rules>
<rules>
<type>response</type>
<source>SignDoctor</source>
<target>AdministerMedicine</target>
</rules>
<rules>
<type>milestone</type>
<source>SignDoctor</source>
<target>AdministerMedicine</target>
</rules>
<rules>
<type>response</type>
<source>DontTrustPrescription(N)</source>
<target>SignDoctor</target>
</rules>
<rules>
<type>response</type>
<source>AcceptPrescription</source>
<target>MakePreparation</target>
</rules>
<rules>
<type>milestone</type>
<source>AcceptPrescription</source>
<target>MakePreparation</target>
</rules>
<rules>
<type>condition</type>
<source>AcceptPrescription</source>
<target>MakePreparation</target>
</rules>
<rules>
<type>response</type>
<source>DontTrustPrescription(CP)</source>
<target>SignDoctor</target>
</rules>
<rules>
<type>response</type>
<source>MakePreparation</source>
<target>SignPA</target>
</rules>
<rules>
<type>condition</type>
<source>MakePreparation</source>
<target>SignPA</target>
</rules>
<rules>
<type>milestone</type>
<source>MakePreparation</source>
<target>SignPA</target>
</rules>
<rules>
<type>response</type>
<source>MakePreparation</source>
<target>SignCP</target>
</rules>
<rules>
<type>condition</type>
<source>SignPA</source>
<target>SignCP</target>
</rules>
<rules>
<type>milestone</type>
<source>SignPA</source>
<target>SignCP</target>
</rules>
<rules>
<type>condition</type>
<source>SignPA</source>
<target>DontTrustPreparation(CP)</target>
</rules>
<rules>
<type>response</type>
<source>DontTrustPreparation(CP)</source>
<target>SignPA</target>
</rules>
<rules>
<type>response</type>
<source>SignCP</source>
<target>Trust</target>
</rules>
<rules>
<type>condition</type>
<source>SignCP</source>
<target>DontTrustPreparation(N)</target>
</rules>
<rules>
<type>response</type>
<source>DontTrustPreparation(N)</source>
<target>SignCP</target>
</rules>
<rules>
<type>condition</type>
<source>Trust</source>
<target>GiveMedicine</target>
</rules>
<rules>
<type>milestone</type>
<source>MedicinePreparation</source>
<target>AdministerMedicine</target>
</rules>
</DCRModel>
""","Use for SC2"),
]
mycursor.executemany(sqlFomular,multi)
db.commit()