# Generated by Django 3.2.8 on 2021-10-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
        migrations.AlterModelTable(
            name='checkedbatchsc',
            table='CheckedBatchSC',
        ),
    ]
