# Generated by Django 3.2.7 on 2021-09-25 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210925_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 25, 21, 53, 34, 45705)),
        ),
    ]
