# Generated by Django 3.2.8 on 2021-11-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LTLTemplate',
            fields=[
                ('lteid', models.CharField(db_collation='utf8_general_ci', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('template_type', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LTLTemplate',
                'managed': False,
            },
        ),
    ]
