# Generated by Django 3.2.7 on 2021-09-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0002_auto_20210928_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
