# Generated by Django 3.2.7 on 2021-09-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0004_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
