# Generated by Django 3.2.7 on 2021-09-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0005_remove_user_last_login'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='ac',
        ),
    ]
