# Generated by Django 3.2.7 on 2021-09-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0008_auto_20210928_2205'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contacts',
        ),
        migrations.AlterModelTable(
            name='user',
            table='accounts',
        ),
    ]
