# Generated by Django 3.2.7 on 2021-09-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0009_auto_20210929_1803'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
