# Generated by Django 3.2.7 on 2021-09-30 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0011_auto_20210930_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
