# Generated by Django 3.2.8 on 2021-10-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('aid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AID')),
                ('username', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True, unique=True)),
                ('password', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('role', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Account',
                'managed': False,
            },
        ),
    ]
