# Generated by Django 3.2.8 on 2021-10-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('cid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AID')),
                ('firstname', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('email', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Contact',
                'managed': False,
            },
        ),
    ]
