# Generated by Django 3.2.4 on 2021-09-13 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_smartcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcontract',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
