# Generated by Django 3.2.6 on 2021-09-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartConstract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('date_modified', models.DateTimeField()),
                ('type', models.CharField(max_length=300)),
            ],
        ),
    ]
