# Generated by Django 3.2.8 on 2021-11-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedBatchSC',
            fields=[
                ('cbsid', models.CharField(db_collation='utf8_general_ci', max_length=64, primary_key=True, serialize=False)),
                ('lnid', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=64, null=True)),
                ('vusid', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=64, null=True)),
                ('ccid', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=64, null=True)),
                ('imid', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=64, null=True)),
                ('noSC', models.IntegerField(null=True)),
                ('checkedDate', models.IntegerField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('result', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CheckedBatchSC',
                'managed': False,
            },
        ),
    ]
