# Generated by Django 3.2.8 on 2021-11-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('blid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='BLID')),
                ('type', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=50, null=True)),
                ('from_value', models.IntegerField(null=True)),
                ('to_value', models.IntegerField(null=True)),
                ('fixed_value', models.IntegerField(null=True)),
                ('range_value', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CheckedSmartContractDetail',
            fields=[
                ('cscid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='CSCID')),
                ('sid', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=64, null=True)),
            ],
            options={
                'db_table': 'CheckedSmartContractDetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CPNContext',
            fields=[
                ('ccid', models.CharField(db_collation='utf8_general_ci', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('context_type', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CPNContext',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IMArgument',
            fields=[
                ('imaid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='IMAID')),
                ('arg_name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('range_from', models.IntegerField(null=True)),
                ('range_to', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'IMArgument',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IMFunction',
            fields=[
                ('imfid', models.CharField(db_collation='utf8_general_ci', max_length=64, primary_key=True, serialize=False)),
                ('sc_name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('func_name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('sender_from', models.IntegerField(null=True)),
                ('sender_to', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'IMFunction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InitialMarking',
            fields=[
                ('imid', models.CharField(db_collation='utf8_general_ci', max_length=64, primary_key=True, serialize=False)),
                ('num_user', models.IntegerField(null=True)),
                ('IM_type', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=50, null=True)),
            ],
            options={
                'db_table': 'InitialMarking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LNAFile',
            fields=[
                ('lnid', models.CharField(db_collation='utf8_general_ci', max_length=64, primary_key=True, serialize=False)),
                ('hcpn_name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('hcpn_content', models.TextField(blank=True, null=True)),
                ('prop_name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('prop_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LNAFile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VulnerabilitySetting',
            fields=[
                ('vusid', models.CharField(db_collation='utf8_general_ci', max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=50, null=True)),
                ('subtype', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=50, null=True)),
                ('formula_id', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=64, null=True)),
                ('formula_name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('formula_description', models.TextField(blank=True, null=True)),
                ('formula_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'VulnerabilitySetting',
                'managed': False,
            },
        ),
    ]
