# Generated by Django 3.2.6 on 2021-09-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='context',
            table='context',
        ),
    ]
