# Generated by Django 3.2.6 on 2021-09-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_alter_context_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='context',
            old_name='content',
            new_name='context',
        ),
    ]
