# Generated by Django 3.2.4 on 2021-10-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0003_rename_content_context_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contexttype',
            fields=[
                ('ctid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contexttype',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='context',
            options={'managed': False},
        ),
    ]
