# Generated by Django 3.2.4 on 2021-09-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartConstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date_modified', models.DateTimeField()),
                ('type', models.CharField(max_length=300)),
                ('aid', models.IntegerField(null=True)),
            ],
        ),
    ]
