# Generated by Django 3.2.6 on 2021-09-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartconstract', '0003_alter_smartconstract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartconstract',
            name='id',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
