# Generated by Django 3.2.6 on 2021-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartconstract', '0004_alter_smartconstract_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('password', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('role', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Smartcontract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('type', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=50, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'smartcontract',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SmartConstract',
        ),
    ]
