# Generated by Django 3.2.8 on 2021-10-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartconstract', '0005_auto_20210928_2205'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
        migrations.AlterModelTable(
            name='smartcontract',
            table='SmartContract',
        ),
    ]
