# Generated by Django 3.2.4 on 2021-08-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355, null=True)),
                ('para', models.CharField(max_length=355, null=True)),
                ('path', models.CharField(max_length=355, null=True)),
                ('lna', models.FileField(null=True, upload_to='')),
                ('out', models.TextField(null=True)),
            ],
        ),
    ]
