# Generated by Django 3.2.8 on 2021-10-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartcontract',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('type', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('created_timestamp', models.IntegerField(null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SmartContract',
                'managed': False,
            },
        ),
    ]
