# Generated by Django 3.2.8 on 2021-11-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('arid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('vartype', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('type', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('value', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Argument',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('bodyContent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Functions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('vartype', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('type', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('value', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
            ],
            options={
                'db_table': 'GlobalVariable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocalVariable',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('vartype', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('type', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('value', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
            ],
            options={
                'db_table': 'LocalVariable',
                'managed': False,
            },
        ),
    ]
