import mysql.connector

db = mysql.connector.connect(
    host = "localhost",
    user="root",
    passwd = '123456',
    database="Project"
)
mycursor = db.cursor()
mycursor.execute("""alter table Contact ADD CONSTRAINT fk_id1 FOREIGN KEY(aid)
references Account (aid);""")
mycursor.execute("""alter table SmartContract ADD CONSTRAINT fk_id2 FOREIGN KEY(aid)
references Account (aid);""")
mycursor.execute("""alter table History ADD CONSTRAINT fk_id3 FOREIGN KEY(scid)
references Account (aid);""")
mycursor.execute("""alter table History_Type ADD CONSTRAINT fk_id4 FOREIGN KEY(hid)
references History (hid);""")
mycursor.execute("""alter table Functions ADD CONSTRAINT fk_id5 FOREIGN KEY(sid)
references SmartContract (sid);""")
mycursor.execute("""alter table GlobalVariable ADD CONSTRAINT fk_id6 FOREIGN KEY(sid)
references SmartContract (sid);""")
mycursor.execute("""alter table LocalVariable ADD CONSTRAINT fk_id7 FOREIGN KEY(fid)
references Functions (fid);""")
mycursor.execute("""alter table Argument ADD CONSTRAINT fk_id8 FOREIGN KEY(fid)
references Functions (fid);""")
mycursor.execute("""alter table CheckedBatchSC ADD CONSTRAINT fk_id9 FOREIGN KEY(aid)
references Account (aid);""")
mycursor.execute("""alter table LTLTemplate ADD CONSTRAINT fk_id10 FOREIGN KEY(ltyid)
references LTLType (ltyid);""")
mycursor.execute("""alter table CPNContext ADD CONSTRAINT fk_id11 FOREIGN KEY(ctid)
references ContextType (ctid);""")
mycursor.execute("""alter table InitialMarking ADD CONSTRAINT fk_id12 FOREIGN KEY(imtid)
references IMTemplate (imtid);""")
mycursor.execute("""alter table CheckedSmartContractDetail ADD CONSTRAINT fk_id13 FOREIGN KEY(lnid)
references LNAFile (lnid);""")
mycursor.execute("""alter table CheckedSmartContractDetail ADD CONSTRAINT fk_id14 FOREIGN KEY(sid)
references SmartContract (sid);""")
mycursor.execute("""alter table CheckedSmartContractDetail ADD CONSTRAINT fk_id15 FOREIGN KEY(lteid)
references LTLTemplate (lteid);""")
mycursor.execute("""alter table CheckedSmartContractDetail ADD CONSTRAINT fk_id16 FOREIGN KEY(cid)
references CPNContext (cid);""")
mycursor.execute("""alter table CheckedSmartContractDetail ADD CONSTRAINT fk_id17 FOREIGN KEY(bid)
references CheckedBatchSC (bid);""")
mycursor.execute("""alter table CheckedSmartContractDetail ADD CONSTRAINT fk_id18 FOREIGN KEY(imid)
references InitialMarking (imid);""")

