# Generated by Django 3.2.4 on 2021-09-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LTLpro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('formular', models.CharField(max_length=300, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('tpid', models.IntegerField(null=True)),
            ],
        ),
    ]
