# Generated by Django 3.2.4 on 2021-09-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LTLpro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ltlpro',
            old_name='formular',
            new_name='fomular',
        ),
    ]
