# Generated by Django 3.2.7 on 2021-09-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LTLpro', '0002_rename_formular_ltlpro_fomular'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ltlpro',
            table='provul',
        ),
    ]
