# Generated by Django 3.2.4 on 2021-10-07 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LTLpro', '0003_alter_ltlpro_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ltlpro',
            options={'managed': False},
        ),
    ]
